# Generated by Django 3.2.3 on 2021-06-19 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkListName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateData', models.DateTimeField(default=datetime.datetime(2021, 6, 20, 0, 8, 32, 765106))),
            ],
        ),
        migrations.CreateModel(
            name='CheckListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('name', 'userId', 'userPassword'), name='unique_user'),
        ),
        migrations.AddField(
            model_name='checklistitems',
            name='checkList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkList.checklist'),
        ),
        migrations.AddField(
            model_name='checklistdata',
            name='checkListItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkList.checklistitems'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkList.user'),
        ),
        migrations.AddConstraint(
            model_name='checklistitems',
            constraint=models.UniqueConstraint(fields=('checkList', 'itemName'), name='unique_checkListItems'),
        ),
        migrations.AddConstraint(
            model_name='checklistdata',
            constraint=models.UniqueConstraint(fields=('checkListItem', 'dateData'), name='unique_checkListData'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(fields=('user', 'checkListName'), name='unique_checkList'),
        ),
    ]
