# Generated by Django 3.2.3 on 2021-05-29 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('checkListName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkListName', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=100)),
                ('dateData', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkListName', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=100)),
            ],
        ),
    ]
