# Generated by Django 3.2.3 on 2021-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkList', '0002_checklist_checklistdata_checklistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitems',
            name='userName',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
